--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonw4331/SimpleReplies
projects:
  SimpleReplies:
    path: ""
    icon: "icon.png"
    lint: false
    excludeDirs:
      - .github
      - build
      - tools
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
...
